before_script:
  - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin

stages:
  - build
  - test
  - release

build:
  stage: build
  except:
    - tags
  script:
    - docker build -t $REGISTRY_USER/$NAME:$CI_COMMIT_SHORT_SHA ./
    - docker push $REGISTRY_USER/$NAME:$CI_COMMIT_SHORT_SHA

test:
  stage: test
  except:
    - tags
  script:
    - docker run --rm -t $REGISTRY_USER/$NAME:$CI_COMMIT_SHORT_SHA pytest /app

release:
  stage: release
  only:
    - tags
  script:
    - docker pull $REGISTRY_USER/$NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $REGISTRY_USER/$NAME:$CI_COMMIT_SHORT_SHA $REGISTRY_USER/$NAME:$CI_COMMIT_TAG
    - docker push $REGISTRY_USER/$NAME:$CI_COMMIT_TAG